<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            ['id'=>7, 'name'=>'Abkhazia','active'=>-1],
            ['id'=>8, 'name'=>'Afghanistan','active'=>-1],
            ['id'=>9, 'name'=>'Albania','active'=> 0],
            ['id'=>10,'name'=>'Algeria','active'=>0],
            ['id'=>11,'name'=>'American Samoa','active'=>0],
            ['id'=>12,'name'=>'Andorra','active'=> 0],
            ['id'=>13,'name'=>'Angola','active'=> -1],
            ['id'=>14,'name'=>'Argentina','active'=> 0],
            ['id'=>15,'name'=>'Armenia','active'=> 0],
            ['id'=>16,'name'=>'Aruba','active'=> 0],
            ['id'=>17,'name'=>'Australia','active'=> 0],
            ['id'=>18,'name'=>'Austria','active'=> 0],
            ['id'=>19,'name'=>'Azerbaijan','active'=> -1],
            ['id'=>20,'name'=>'Bahamas','active'=> -1],
            ['id'=>21,'name'=>'Bahrain','active'=> -1],
            ['id'=>22,'name'=>'Bangladesh','active'=> -1],
            ['id'=>23,'name'=>'Barbados','active'=> -1],
            ['id'=>24,'name'=>'Belgium','active'=> 0],
            ['id'=>25,'name'=>'Belize','active'=> -1],
            ['id'=>26,'name'=>'Benin','active'=> -1],
            ['id'=>27,'name'=>'Bermuda','active'=> -1],
            ['id'=>28,'name'=>'Bhutan','active'=> -1],
            ['id'=>29,'name'=>'Bolivia','active'=> 0],
            ['id'=>30,'name'=>'Bosnia and Herzegovina','active'=>0],
            ['id'=>31,'name'=>'Botswana','active'=>0],
            ['id'=>32,'name'=>'Brazil','active'=>0],
            ['id'=>33,'name'=>'Brunei','active'=>-1],
            ['id'=>34,'name'=>'Bulgaria','active'=>0],
            ['id'=>35,'name'=>'Burkina Faso','active'=>-1],
            ['id'=>36,'name'=>'Burma','active'=>-1],
            ['id'=>37,'name'=>'Burundi','active'=>-1],
            ['id'=>38,'name'=>'Cambodia','active'=>-1],
            ['id'=>39,'name'=>'Cameroon','active'=>-1],
            ['id'=>40,'name'=>'Canada','active'=>0],
            ['id'=>41,'name'=>'Canary Islands','active'=>0],
            ['id'=>42,'name'=>'Cape Verde','active'=>-1],
            ['id'=>43,'name'=>'Central African Republic','active'=>-1],
            ['id'=>44,'name'=>'Chad','active'=>-1],
            ['id'=>45,'name'=>'Chile','active'=>0],
            ['id'=>46,'name'=>'China','active'=>0],
            ['id'=>47,'name'=>'Colombia','active'=>0],
            ['id'=>48,'name'=>'Comoros','active'=>-1],
            ['id'=>49,'name'=>'Congo','active'=>-1],
            ['id'=>50,'name'=>'Congo - DRC','active'=>-1],
            ['id'=>51,'name'=>'Costa Rica','active'=>0],
            ['id'=>52,'name'=>'Cote d Ivoire','active'=>-1],
            ['id'=>53,'name'=>'Croatia','active'=>0],
            ['id'=>54,'name'=>'Cuba','active'=>-1],
            ['id'=>55,'name'=>'Cyprus','active'=>0],
            ['id'=>56,'name'=>'Czech Republic','active'=>0],
            ['id'=>57,'name'=>'Denmark','active'=>0],
            ['id'=>58,'name'=>'Djibouti','active'=>-1],
            ['id'=>59,'name'=>'Dominican Republic','active'=>-1],
            ['id'=>60,'name'=>'Ecuador','active'=>-1],
            ['id'=>61,'name'=>'Egypt','active'=>0],
            ['id'=>62,'name'=>'El Salvador','active'=>0],
            ['id'=>63,'name'=>'Equatorial Guinea','active'=>-1],
            ['id'=>64,'name'=>'Eritrea','active'=>-1],
            ['id'=>65,'name'=>'Estonia','active'=>0],
            ['id'=>66,'name'=>'Ethiopia','active'=>-1],
            ['id'=>67,'name'=>'Falkland Islands','active'=>0],
            ['id'=>68,'name'=>'Federated States of Micronesia','active'=>0],
            ['id'=>69,'name'=>'Fiji','active'=>0],
            ['id'=>70,'name'=>'Finland','active'=>0],
            ['id'=>71,'name'=>'France','active'=>0],
            ['id'=>72,'name'=>'French Guiana','active'=>0],
            ['id'=>73,'name'=>'French Polynesia','active'=>0],
            ['id'=>74,'name'=>'Gabon','active'=>-1],
            ['id'=>75,'name'=>'Palestine','active'=>-1],
            ['id'=>76,'name'=>'Georgia','active'=>0],
            ['id'=>77,'name'=>'Germany','active'=>0],
            ['id'=>78,'name'=>'Ghana','active'=>-1],
            ['id'=>79,'name'=>'Gibraltar','active'=>0],
            ['id'=>80,'name'=>'Greece','active'=>0],
            ['id'=>81,'name'=>'Grenada','active'=>-1],
            ['id'=>82,'name'=>'Guadeloupe','active'=>0],
            ['id'=>83,'name'=>'Guatemala','active'=>-1],
            ['id'=>84,'name'=>'Guinea Conakry','active'=>-1],
            ['id'=>85,'name'=>'Guinea-Bissau','active'=>-1],
            ['id'=>86,'name'=>'Guyana','active'=>0],
            ['id'=>87,'name'=>'Haiti','active'=>-1],
            ['id'=>88,'name'=>'Honduras','active'=>-1],
            ['id'=>89,'name'=>'Hong Kong','active'=>-1],
            ['id'=>90,'name'=>'Hungary','active'=>0],
            ['id'=>91,'name'=>'Iceland','active'=>0],
            ['id'=>92,'name'=>'India','active'=>0],
            ['id'=>93,'name'=>'Indonesia','active'=>0],
            ['id'=>94,'name'=>'Iran','active'=>0],
            ['id'=>95,'name'=>'Iraq','active'=>-1],
            ['id'=>96,'name'=>'Ireland','active'=>0],
            ['id'=>97,'name'=>'Israel','active'=>-1],
            ['id'=>98,'name'=>'Italy','active'=>0],
            ['id'=>99,'name'=>'Jamaica','active'=>-1],
            ['id'=>100,'name'=>'Japan','active'=>0],
            ['id'=>101,'name'=>'Jordan','active'=>-1],
            ['id'=>102,'name'=>'Kenya','active'=>-1],
            ['id'=>103,'name'=>'Kirgizya','active'=>-1],
            ['id'=>104,'name'=>'Kosovo','active'=>0],
            ['id'=>105,'name'=>'Kuwait','active'=>-1],
            ['id'=>106,'name'=>'Kyrgyzstan','active'=>-1],
            ['id'=>107,'name'=>'Laos','active'=>-1],
            ['id'=>108,'name'=>'Latvia','active'=>0],
            ['id'=>109,'name'=>'Lebanon','active'=>-1],
            ['id'=>110,'name'=>'Lesotho','active'=>0],
            ['id'=>111,'name'=>'Liberia','active'=>-1],
            ['id'=>112,'name'=>'Libya','active'=>-1],
            ['id'=>113,'name'=>'Liechtenstein','active'=>0],
            ['id'=>114,'name'=>'Lithuania','active'=>0],
            ['id'=>115,'name'=>'Luxembourg','active'=>0],
            ['id'=>116,'name'=>'Macau','active'=>-1],
            ['id'=>117,'name'=>'Macedonia','active'=>0],
            ['id'=>118,'name'=>'Madagascar','active'=>-1],
            ['id'=>119,'name'=>'Malawi','active'=>-1],
            ['id'=>120,'name'=>'Malaysia','active'=>-1],
            ['id'=>121,'name'=>'Maldives','active'=>0],
            ['id'=>122,'name'=>'Mali','active'=>-1],
            ['id'=>123,'name'=>'Malta','active'=>0],
            ['id'=>124,'name'=>'Martinique','active'=>0],
            ['id'=>125,'name'=>'Mauritania','active'=>-1],
            ['id'=>126,'name'=>'Mauritius','active'=>-1],
            ['id'=>127,'name'=>'Mayotte','active'=>0],
            ['id'=>128,'name'=>'Mexico','active'=>0],
            ['id'=>129,'name'=>'Moldova','active'=>-1],
            ['id'=>130,'name'=>'Monaco','active'=>0],
            ['id'=>131,'name'=>'Mongolia','active'=>-1],
            ['id'=>132,'name'=>'Montenegro','active'=>0],
            ['id'=>133,'name'=>'Montserrat','active'=>0],
            ['id'=>134,'name'=>'Morocco','active'=>0],
            ['id'=>135,'name'=>'Mozambique','active'=>-1],
            ['id'=>136,'name'=>'Namibia','active'=>0],
            ['id'=>137,'name'=>'Nepal','active'=>-1],
            ['id'=>138,'name'=>'Netherlands','active'=>0],
            ['id'=>139,'name'=>'Netherlands Antilles','active'=>0],
            ['id'=>140,'name'=>'New Caledonia','active'=>0],
            ['id'=>141,'name'=>'New Zealand','active'=>0],
            ['id'=>142,'name'=>'Nicaragua','active'=>-1],
            ['id'=>143,'name'=>'Niger','active'=>-1],
            ['id'=>144,'name'=>'Nigeria','active'=>-1],
            ['id'=>145,'name'=>'North Korea','active'=>0],
            ['id'=>146,'name'=>'Norway','active'=>0],
            ['id'=>147,'name'=>'Oman','active'=>-1],
            ['id'=>148,'name'=>'Pakistan','active'=>-1],
            ['id'=>149,'name'=>'Panama','active'=>-1],
            ['id'=>150,'name'=>'Papua New Guinea','active'=>-1],
            ['id'=>151,'name'=>'Paraguay','active'=>0],
            ['id'=>152,'name'=>'Peru','active'=>0],
            ['id'=>153,'name'=>'Philippines','active'=>0],
            ['id'=>154,'name'=>'Poland','active'=>0],
            ['id'=>155,'name'=>'Portugal','active'=>0],
            ['id'=>156,'name'=>'Puerto Rico','active'=>0],
            ['id'=>157,'name'=>'Qatar','active'=>-1],
            ['id'=>158,'name'=>'Reunion','active'=>0],
            ['id'=>159,'name'=>'Romania','active'=>0],
            ['id'=>160,'name'=>'Rwanda','active'=>-1],
            ['id'=>161,'name'=>'Saint Pierre and Miquelon','active'=>0],
            ['id'=>162,'name'=>'Samoa','active'=>-1],
            ['id'=>163,'name'=>'San Marino','active'=>0],
            ['id'=>164,'name'=>'Sao Tome and Principe','active'=>-1],
            ['id'=>165,'name'=>'Saudi Arabia','active'=>0],
            ['id'=>166,'name'=>'Senegal','active'=>-1],
            ['id'=>167,'name'=>'Serbia and Montenegro (Yugoslavia)','active'=>0],
            ['id'=>168,'name'=>'Seychelles','active'=>-1],
            ['id'=>169,'name'=>'Sierra Leone','active'=>-1],
            ['id'=>170,'name'=>'Singapore','active'=>0],
            ['id'=>171,'name'=>'Slovakia','active'=>0],
            ['id'=>172,'name'=>'Slovenia','active'=>0],
            ['id'=>173,'name'=>'Somalia','active'=>-1],
            ['id'=>174,'name'=>'South Africa','active'=>0],
            ['id'=>175,'name'=>'South Korea','active'=>0],
            ['id'=>176,'name'=>'Spain','active'=>0],
            ['id'=>177,'name'=>'Sri Lanka','active'=>-1],
            ['id'=>178,'name'=>'Sudan','active'=>-1],
            ['id'=>179,'name'=>'Suriname','active'=>-1],
            ['id'=>180,'name'=>'Swaziland','active'=>-1],
            ['id'=>181,'name'=>'Sweden','active'=>0],
            ['id'=>182,'name'=>'Switzerland','active'=>0],
            ['id'=>183,'name'=>'Syria','active'=>-1],
            ['id'=>184,'name'=>'Taiwan','active'=>0],
            ['id'=>185,'name'=>'Tajikistan','active'=>-1],
            ['id'=>186,'name'=>'Tanzania','active'=>-1],
            ['id'=>187,'name'=>'Thailand','active'=>-1],
            ['id'=>188,'name'=>'The Gambia','active'=>-1],
            ['id'=>189,'name'=>'Togo','active'=>-1],
            ['id'=>190,'name'=>'Tonga','active'=>-1],
            ['id'=>191,'name'=>'Trinidad and Tobago','active'=>-1],
            ['id'=>192,'name'=>'Tunisia','active'=>0],
            ['id'=>193,'name'=>'Turkey','active'=>-1],
            ['id'=>194,'name'=>'Turkmenistan','active'=>-1],
            ['id'=>195,'name'=>'Uganda','active'=>-1],
            ['id'=>196,'name'=>'Ukraine','active'=>0],
            ['id'=>197,'name'=>'United Arab Emirates','active'=>-1],
            ['id'=>198,'name'=>'United Kingdom','active'=>0],
            ['id'=>199,'name'=>'USA','active'=>0],
            ['id'=>200,'name'=>'Uruguay','active'=>0],
            ['id'=>201,'name'=>'Uzbekistan','active'=>0],
            ['id'=>202,'name'=>'Venezuela','active'=>0],
            ['id'=>203,'name'=>'Vietnam','active'=>0],
            ['id'=>204,'name'=>'Yemen','active'=>-1],
            ['id'=>205,'name'=>'Yugoslavia (Serbia and Montenegro)','active'=>0],
            ['id'=>206,'name'=>'Zambia','active'=>-1],
            ['id'=>207,'name'=>'Zimbabwe','active'=>-1],
            ['id'=>208,'name'=>'Russia (West)','active'=>0],
            ['id'=>209,'name'=>'Kazakhstan','active'=>0],
            ['id'=>210,'name'=>'Belorussia','active'=>0],
            ['id'=>211,'name'=>'Russia (East)','active'=>0],
            ['id'=>212,'name'=>'British Virgin Islands','active'=>-1],
        ]);
    }
}