<?php

use Illuminate\Database\Seeder;

class PortySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ports')->insert([
            ['id'=>1,'name'=>'Ho Chi Minh - Cat Lai','country_id'=>203,'status'=>1],
            ['id'=>2,'name'=>'Luanda','country_id'=>13,'status'=>1],
            ['id'=>3,'name'=>'Buenos Aires','country_id'=>14,'status'=>1],
            ['id'=>4,'name'=>'Santos','country_id'=>32,'status'=>1],
            ['id'=>5,'name'=>'Rio Grande','country_id'=>32,'status'=>1],
            ['id'=>6,'name'=>'Paranagua','country_id'=>32,'status'=>1],
            ['id'=>7,'name'=>'Itajai','country_id'=>32,'status'=>1],
            ['id'=>8,'name'=>'Navegantes','country_id'=>32,'status'=>1],
            ['id'=>9,'name'=>'Rio de Janeiro','country_id'=>32,'status'=>1],
            ['id'=>10,'name'=>'Sepetiba','country_id'=>32,'status'=>1],
            ['id'=>11,'name'=>'Abidjan','country_id'=>52,'status'=>1],
            ['id'=>12,'name'=>'Muscat','country_id'=>147,'status'=>1],
            ['id'=>13,'name'=>'Manama','country_id'=>21,'status'=>1],
            ['id'=>14,'name'=>'Jebel Ali','country_id'=>197,'status'=>1],
            ['id'=>15,'name'=>'Sharjah','country_id'=>197,'status'=>1],
            ['id'=>16,'name'=>'Jeddah','country_id'=>165,'status'=>1],
            ['id'=>17,'name'=>'Cape Town','country_id'=>174,'status'=>1],
            ['id'=>18,'name'=>'Durban','country_id'=>174,'status'=>1],
            ['id'=>19,'name'=>'Libreville','country_id'=>74,'status'=>1],
            ['id'=>20,'name'=>'Port Gentil','country_id'=>74,'status'=>1],
            ['id'=>21,'name'=>'Pointe Noire','country_id'=>49,'status'=>1],
            ['id'=>22,'name'=>'Matadi','country_id'=>50,'status'=>1],
            ['id'=>23,'name'=>'St Petersburg','country_id'=>208,'status'=>1],
            ['id'=>24,'name'=>'Kaliningrad','country_id'=>208,'status'=>1],
            ['id'=>25,'name'=>'Vladivostok','country_id'=>211,'status'=>1],
            ['id'=>26,'name'=>'Magadan','country_id'=>211,'status'=>1],
            ['id'=>27,'name'=>'Poti','country_id'=>76,'status'=>1],
            ['id'=>28,'name'=>'Poti-Transit','country_id'=>15,'status'=>1],
            ['id'=>29,'name'=>'Mersin','country_id'=>193,'status'=>1],
            ['id'=>30,'name'=>'Douala','country_id'=>39,'status'=>1],
            ['id'=>31,'name'=>'Apapa','country_id'=>144,'status'=>1],
            ['id'=>32,'name'=>'Cotonou','country_id'=>26,'status'=>1],
            ['id'=>33,'name'=>'Tema','country_id'=>78,'status'=>1],
            ['id'=>34,'name'=>'Aden','country_id'=>204,'status'=>1],
            ['id'=>35,'name'=>'Shuwaikh','country_id'=>105,'status'=>1],
            ['id'=>36,'name'=>'Doha','country_id'=>157,'status'=>1],
            ['id'=>37,'name'=>'Dammam','country_id'=>165,'status'=>1],
            ['id'=>38,'name'=>'Savannah','country_id'=>199,'status'=>1],
            ['id'=>39,'name'=>'Mobile','country_id'=>199,'status'=>1],
            ['id'=>40,'name'=>'Oakland','country_id'=>199,'status'=>1],
            ['id'=>41,'name'=>'Norfolk','country_id'=>199,'status'=>1],
            ['id'=>42,'name'=>'Antwerp','country_id'=>24,'status'=>1],
            ['id'=>43,'name'=>'Hamburg','country_id'=>77,'status'=>1],
            ['id'=>44,'name'=>'Bremenhaven','country_id'=>77,'status'=>1],
            ['id'=>45,'name'=>'Le Havre','country_id'=>71,'status'=>1],
            ['id'=>46,'name'=>'Marseille','country_id'=>71,'status'=>1],
            ['id'=>47,'name'=>'Rotterdam','country_id'=>138,'status'=>1],
            ['id'=>48,'name'=>'Klaipeda','country_id'=>114,'status'=>1],
            ['id'=>49,'name'=>'Riga','country_id'=>108,'status'=>1],
            ['id'=>50,'name'=>'Tallinn','country_id'=>65,'status'=>1],
            ['id'=>51,'name'=>'Copenhagen','country_id'=>57,'status'=>1],
            ['id'=>52,'name'=>'El Callao','country_id'=>152,'status'=>1],
            ['id'=>53,'name'=>'San Antonio','country_id'=>45,'status'=>1],
            ['id'=>54,'name'=>'Valparaiso','country_id'=>45,'status'=>1],
            ['id'=>55,'name'=>'Walwis Bay','country_id'=>136,'status'=>1],
            ['id'=>56,'name'=>'Djibouti','country_id'=>58,'status'=>1],
            ['id'=>57,'name'=>'Salalah','country_id'=>147,'status'=>1],
            ['id'=>58,'name'=>'Hong Kong','country_id'=>89,'status'=>1],
            ['id'=>59,'name'=>'Shanghai','country_id'=>46,'status'=>1],
            ['id'=>60,'name'=>'Yantian','country_id'=>46,'status'=>1],
            ['id'=>61,'name'=>'Shenzhen','country_id'=>46,'status'=>1],
            ['id'=>62,'name'=>'Danang','country_id'=>203,'status'=>1],
            ['id'=>63,'name'=>'Haiphong','country_id'=>203,'status'=>1],
            ['id'=>64,'name'=>'Ho Chi Minh - ICD Phuoc Long','country_id'=>203,'status'=>1],
            ['id'=>65,'name'=>'Montreal','country_id'=>40,'status'=>1],
            ['id'=>66,'name'=>'Vancouver','country_id'=>40,'status'=>1],
            ['id'=>67,'name'=>'Iquique','country_id'=>45,'status'=>1],
            ['id'=>68,'name'=>'Puerto Cabelo','country_id'=>202,'status'=>1],
            ['id'=>69,'name'=>'Cartagena','country_id'=>47,'status'=>1],
            ['id'=>70,'name'=>'Kingston','country_id'=>99,'status'=>1],
            ['id'=>71,'name'=>'Port-Au-Prince','country_id'=>87,'status'=>1],
            ['id'=>72,'name'=>'Bandar Abas','country_id'=>94,'status'=>1],
            ['id'=>73,'name'=>'Managua','country_id'=>142,'status'=>1],
            ['id'=>74,'name'=>'Barcelona','country_id'=>176,'status'=>1],
            ['id'=>75,'name'=>'Montevideo','country_id'=>200,'status'=>1],
            ['id'=>76,'name'=>'Manzanillo','country_id'=>128,'status'=>1],
            ['id'=>77,'name'=>'Araputanga','country_id'=>32,'status'=>1],
            ['id'=>78,'name'=>'Santa Cruz de la Sierra','country_id'=>29,'status'=>1],
            ['id'=>79,'name'=>'Any US Port','country_id'=>199,'status'=>1],
            ['id'=>80,'name'=>'Ilychevsk','country_id'=>196,'status'=>1],
            ['id'=>81,'name'=>'Mindelo','country_id'=>42,'status'=>1],
            ['id'=>82,'name'=>'Odessa','country_id'=>196,'status'=>1],
            ['id'=>83,'name'=>'Any Brazilian port','country_id'=>32,'status'=>1],
            ['id'=>84,'name'=>'Any Irish Port','country_id'=>96,'status'=>1],
            ['id'=>85,'name'=>'Busan','country_id'=>175,'status'=>1],
            ['id'=>86,'name'=>'New Orleans','country_id'=>199,'status'=>1],
            ['id'=>87,'name'=>'Asuncion','country_id'=>151,'status'=>1],
            ['id'=>88,'name'=>'CORINTO','country_id'=>142,'status'=>1],
            ['id'=>89,'name'=>'Leam Chabang','country_id'=>187,'status'=>1],
            ['id'=>90,'name'=>'BANGKOK','country_id'=>187,'status'=>1],
            ['id'=>91,'name'=>'DUBLIN','country_id'=>96,'status'=>1],
            ['id'=>92,'name'=>'San Vicente','country_id'=>45,'status'=>1],
            ['id'=>93,'name'=>'Ningbo','country_id'=>46,'status'=>1],
            ['id'=>94,'name'=>'Arica','country_id'=>45,'status'=>1],
            ['id'=>95,'name'=>'Santiago','country_id'=>45,'status'=>1],
            ['id'=>96,'name'=>'Las Condes','country_id'=>45,'status'=>1],
            ['id'=>97,'name'=>'Male','country_id'=>121,'status'=>1],
            ['id'=>98,'name'=>'XINGANG','country_id'=>46,'status'=>1],
            ['id'=>99,'name'=>'Newark','country_id'=>199,'status'=>1],
            ['id'=>100,'name'=>'LIMA','country_id'=>152,'status'=>1],
            ['id'=>101,'name'=>'Maputo','country_id'=>135,'status'=>1],
            ['id'=>102,'name'=>'Laem Chabang','country_id'=>187,'status'=>1],
            ['id'=>103,'name'=>'Guayaquil','country_id'=>60,'status'=>1],
            ['id'=>104,'name'=>'Puerto Madryn','country_id'=>14,'status'=>1],
            ['id'=>105,'name'=>'Fuzhou','country_id'=>46,'status'=>1],
            ['id'=>106,'name'=>'Seattle','country_id'=>199,'status'=>1],
            ['id'=>107,'name'=>'Vila do Conde','country_id'=>32,'status'=>1],
            ['id'=>108,'name'=>'Mazatlan','country_id'=>128,'status'=>1],
            ['id'=>109,'name'=>'Altamira','country_id'=>128,'status'=>1],
            ['id'=>110,'name'=>'CABINDA','country_id'=>13,'status'=>1],
            ['id'=>111,'name'=>'Any Chinese port','country_id'=>46,'status'=>1],
            ['id'=>112,'name'=>'To Be Advised','country_id'=>46,'status'=>1],
            ['id'=>113,'name'=>'Any place Brazil','country_id'=>32,'status'=>1],
            ['id'=>114,'name'=>'Penang','country_id'=>120,'status'=>1],
            ['id'=>115,'name'=>'Xiamen','country_id'=>46,'status'=>1],
            ['id'=>116,'name'=>'Dalian','country_id'=>46,'status'=>1],
            ['id'=>117,'name'=>'Houston','country_id'=>199,'status'=>1],
            ['id'=>118,'name'=>'Singapore','country_id'=>170,'status'=>1],
            ['id'=>119,'name'=>'Tapejara','country_id'=>32,'status'=>1],
            ['id'=>120,'name'=>'Mar Del Plata','country_id'=>14,'status'=>1],
            ['id'=>121,'name'=>'Any Canadian Port','country_id'=>40,'status'=>1],
            ['id'=>122,'name'=>'Warszawa','country_id'=>154,'status'=>1],
            ['id'=>123,'name'=>'Kosow Lacki','country_id'=>154,'status'=>1],
            ['id'=>124,'name'=>'Kong Toey','country_id'=>187,'status'=>1],
            ['id'=>125,'name'=>'Any Place Argentina','country_id'=>14,'status'=>1],
            ['id'=>126,'name'=>'Bogota','country_id'=>47,'status'=>1],
            ['id'=>127,'name'=>'Nava Sheva','country_id'=>92,'status'=>1],
            ['id'=>128,'name'=>'Any Malasyan Port','country_id'=>120,'status'=>1],
            ['id'=>129,'name'=>'Johor','country_id'=>120,'status'=>1],
            ['id'=>130,'name'=>'Any Asian Port','country_id'=>120,'status'=>1],
            ['id'=>131,'name'=>'Chennai','country_id'=>92,'status'=>1],
            ['id'=>132,'name'=>'Rosario','country_id'=>14,'status'=>1],
            ['id'=>133,'name'=>'Tianjin','country_id'=>46,'status'=>1],
            ['id'=>134,'name'=>'Balboa','country_id'=>149,'status'=>1],
            ['id'=>135,'name'=>'Bangkok BMT Terminal','country_id'=>187,'status'=>1],
            ['id'=>136,'name'=>'Barranquilla','country_id'=>47,'status'=>1],
            ['id'=>137,'name'=>'Qingdao','country_id'=>46,'status'=>1],
            ['id'=>138,'name'=>'Crespo','country_id'=>14,'status'=>1],
            ['id'=>139,'name'=>'Walvis Bay','country_id'=>136,'status'=>1],
            ['id'=>140,'name'=>'Chongqin','country_id'=>46,'status'=>1],
            ['id'=>141,'name'=>'Izmir','country_id'=>193,'status'=>1],
            ['id'=>142,'name'=>'Any Polish port','country_id'=>154,'status'=>1],
            ['id'=>143,'name'=>'Mawei, Fuzhou','country_id'=>46,'status'=>1],
            ['id'=>144,'name'=>'Beirut','country_id'=>109,'status'=>1],
            ['id'=>145,'name'=>'Miami','country_id'=>199,'status'=>1],
            ['id'=>146,'name'=>'Sumare','country_id'=>32,'status'=>1],
            ['id'=>147,'name'=>'Gdansk','country_id'=>154,'status'=>1],
            ['id'=>148,'name'=>'Dakar','country_id'=>166,'status'=>1],
            ['id'=>149,'name'=>'Monrovia','country_id'=>111,'status'=>1],
            ['id'=>150,'name'=>'Banjul','country_id'=>188,'status'=>1],
            ['id'=>151,'name'=>'Freetown','country_id'=>169,'status'=>1],
            ['id'=>152,'name'=>'Aqaba','country_id'=>101,'status'=>1],
            ['id'=>153,'name'=>'Um Qsar','country_id'=>95,'status'=>1],
            ['id'=>154,'name'=>'Nouakchott','country_id'=>125,'status'=>1],
            ['id'=>155,'name'=>'Nouhadibou','country_id'=>125,'status'=>1],
            ['id'=>156,'name'=>'Karachi','country_id'=>148,'status'=>1],
            ['id'=>157,'name'=>'Valencia','country_id'=>176,'status'=>1],
            ['id'=>158,'name'=>'Lazaro Cardenas','country_id'=>128,'status'=>1],
            ['id'=>159,'name'=>'Manila','country_id'=>153,'status'=>1],
            ['id'=>160,'name'=>'La Guaira','country_id'=>202,'status'=>1],
            ['id'=>161,'name'=>'Santo Domingo','country_id'=>59,'status'=>1],
            ['id'=>162,'name'=>'Seoul','country_id'=>175,'status'=>1],
            ['id'=>163,'name'=>'Zarate','country_id'=>14,'status'=>1],
            ['id'=>164,'name'=>'Napier','country_id'=>141,'status'=>1],
            ['id'=>165,'name'=>'Mumbai','country_id'=>92,'status'=>1],
            ['id'=>166,'name'=>'zanzibar','country_id'=>186,'status'=>1],
            ['id'=>167,'name'=>'Cai Mep Vung Tau','country_id'=>203,'status'=>1],
            ['id'=>168,'name'=>'Napoles','country_id'=>98,'status'=>1],
            ['id'=>169,'name'=>'Salerno','country_id'=>98,'status'=>1],
            ['id'=>170,'name'=>'Zhang Jia Gang','country_id'=>46,'status'=>1],
            ['id'=>171,'name'=>'Toronto','country_id'=>40,'status'=>1],
            ['id'=>172,'name'=>'Alexandria','country_id'=>61,'status'=>1],
            ['id'=>173,'name'=>'Buenaventura','country_id'=>47,'status'=>1],
            ['id'=>174,'name'=>'Kaohsiung','country_id'=>184,'status'=>1],
            ['id'=>175,'name'=>'Varna','country_id'=>34,'status'=>1],
            ['id'=>176,'name'=>'FELIXSTOWE','country_id'=>198,'status'=>1],
            ['id'=>177,'name'=>'PLOCE','country_id'=>53,'status'=>1],
            ['id'=>178,'name'=>'COLOMBO','country_id'=>177,'status'=>1],
            ['id'=>179,'name'=>'Conakry','country_id'=>84,'status'=>1],
            ['id'=>180,'name'=>'PUERTO DESEADO','country_id'=>14,'status'=>1],
            ['id'=>181,'name'=>'ITAGUAI','country_id'=>47,'status'=>1],
            ['id'=>182,'name'=>'ITAPOA','country_id'=>32,'status'=>1],
            ['id'=>183,'name'=>'SALVADOR','country_id'=>142,'status'=>1],
            ['id'=>184,'name'=>'LAT KRABANG','country_id'=>187,'status'=>1],
            ['id'=>185,'name'=>'ITAJI','country_id'=>32,'status'=>1],
            ['id'=>186,'name'=>'QUINGDAO','country_id'=>46,'status'=>1],
            ['id'=>187,'name'=>'XIANGANG','country_id'=>46,'status'=>1],
        ]);
    }
}

